'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.18444
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceHotel
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://reservation", ConfigurationName:="ServiceHotel.FacadeServiceWeb")>  _
    Public Interface FacadeServiceWeb
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Entite)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(EntiteDTO))>  _
        Function update(ByVal chambreDTO As ServiceHotel.Formulaire) As <System.ServiceModel.MessageParameterAttribute(Name:="updateReturn")> Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function updateAsync(ByVal chambreDTO As ServiceHotel.Formulaire) As <System.ServiceModel.MessageParameterAttribute(Name:="updateReturn")> System.Threading.Tasks.Task(Of Boolean)
        
        'CODEGEN : Le paramètre 'obtenirListeClientsReturn' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Entite)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(EntiteDTO))>  _
        Function obtenirListeClients(ByVal request As ServiceHotel.obtenirListeClientsRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="obtenirListeClientsReturn")> ServiceHotel.obtenirListeClientsResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function obtenirListeClientsAsync(ByVal request As ServiceHotel.obtenirListeClientsRequest) As System.Threading.Tasks.Task(Of ServiceHotel.obtenirListeClientsResponse)
        
        'CODEGEN : Le paramètre 'obtenirReservationsReturn' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Entite)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(EntiteDTO))>  _
        Function obtenirReservations(ByVal request As ServiceHotel.obtenirReservationsRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="obtenirReservationsReturn")> ServiceHotel.obtenirReservationsResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function obtenirReservationsAsync(ByVal request As ServiceHotel.obtenirReservationsRequest) As System.Threading.Tasks.Task(Of ServiceHotel.obtenirReservationsResponse)
        
        'CODEGEN : Le paramètre 'obtenirListeChambreReturn' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Entite)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(EntiteDTO))>  _
        Function obtenirListeChambre(ByVal request As ServiceHotel.obtenirListeChambreRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="obtenirListeChambreReturn")> ServiceHotel.obtenirListeChambreResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function obtenirListeChambreAsync(ByVal request As ServiceHotel.obtenirListeChambreRequest) As System.Threading.Tasks.Task(Of ServiceHotel.obtenirListeChambreResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dto.reservation")>  _
    Partial Public Class Formulaire
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private dateModificationField As String
        
        Private modifiantField As Integer
        
        Private reservationField As ReservationDTO
        
        Private typeField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property dateModification() As String
            Get
                Return Me.dateModificationField
            End Get
            Set
                Me.dateModificationField = value
                Me.RaisePropertyChanged("dateModification")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property modifiant() As Integer
            Get
                Return Me.modifiantField
            End Get
            Set
                Me.modifiantField = value
                Me.RaisePropertyChanged("modifiant")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property reservation() As ReservationDTO
            Get
                Return Me.reservationField
            End Get
            Set
                Me.reservationField = value
                Me.RaisePropertyChanged("reservation")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property type() As Integer
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
                Me.RaisePropertyChanged("type")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dto.reservation")>  _
    Partial Public Class ReservationDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arriveeField As String
        
        Private chambreDTOField As ChambreDTO
        
        Private clientDTOField As ClientDTO
        
        Private creationField As String
        
        Private departField As String
        
        Private idReservationField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property arrivee() As String
            Get
                Return Me.arriveeField
            End Get
            Set
                Me.arriveeField = value
                Me.RaisePropertyChanged("arrivee")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property chambreDTO() As ChambreDTO
            Get
                Return Me.chambreDTOField
            End Get
            Set
                Me.chambreDTOField = value
                Me.RaisePropertyChanged("chambreDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property clientDTO() As ClientDTO
            Get
                Return Me.clientDTOField
            End Get
            Set
                Me.clientDTOField = value
                Me.RaisePropertyChanged("clientDTO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property creation() As String
            Get
                Return Me.creationField
            End Get
            Set
                Me.creationField = value
                Me.RaisePropertyChanged("creation")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property depart() As String
            Get
                Return Me.departField
            End Get
            Set
                Me.departField = value
                Me.RaisePropertyChanged("depart")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property idReservation() As Integer
            Get
                Return Me.idReservationField
            End Get
            Set
                Me.idReservationField = value
                Me.RaisePropertyChanged("idReservation")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dto.reservation")>  _
    Partial Public Class ChambreDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private numeroChambreField As Integer
        
        Private reservationsField() As ReservationDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property numeroChambre() As Integer
            Get
                Return Me.numeroChambreField
            End Get
            Set
                Me.numeroChambreField = value
                Me.RaisePropertyChanged("numeroChambre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true, Order:=1),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", [Namespace]:="http://reservation", IsNullable:=false)>  _
        Public Property reservations() As ReservationDTO()
            Get
                Return Me.reservationsField
            End Get
            Set
                Me.reservationsField = value
                Me.RaisePropertyChanged("reservations")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://arbre.reservation")>  _
    Partial Public Class ArbreBinaireReservations
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(Client)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://entites.reservation")>  _
    Partial Public Class Entite
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private reservationsField As ArbreBinaireReservations
        
        Private reservationsArrayField() As ReservationDTO
        
        Private reservationsFromDTOField() As ReservationDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property reservations() As ArbreBinaireReservations
            Get
                Return Me.reservationsField
            End Get
            Set
                Me.reservationsField = value
                Me.RaisePropertyChanged("reservations")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true, Order:=1),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", [Namespace]:="http://reservation", IsNullable:=false)>  _
        Public Property reservationsArray() As ReservationDTO()
            Get
                Return Me.reservationsArrayField
            End Get
            Set
                Me.reservationsArrayField = value
                Me.RaisePropertyChanged("reservationsArray")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true, Order:=2),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", [Namespace]:="http://reservation", IsNullable:=false)>  _
        Public Property reservationsFromDTO() As ReservationDTO()
            Get
                Return Me.reservationsFromDTOField
            End Get
            Set
                Me.reservationsFromDTOField = value
                Me.RaisePropertyChanged("reservationsFromDTO")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://objects.reservation")>  _
    Partial Public Class Client
        Inherits Entite
        
        Private idClientField As Integer
        
        Private nomField As String
        
        Private prenomField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property idClient() As Integer
            Get
                Return Me.idClientField
            End Get
            Set
                Me.idClientField = value
                Me.RaisePropertyChanged("idClient")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property nom() As String
            Get
                Return Me.nomField
            End Get
            Set
                Me.nomField = value
                Me.RaisePropertyChanged("nom")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property prenom() As String
            Get
                Return Me.prenomField
            End Get
            Set
                Me.prenomField = value
                Me.RaisePropertyChanged("prenom")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(ClientDTO)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dto.reservation")>  _
    Partial Public Class EntiteDTO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private reservationsField() As ReservationDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true, Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", [Namespace]:="http://reservation", IsNullable:=false)>  _
        Public Property reservations() As ReservationDTO()
            Get
                Return Me.reservationsField
            End Get
            Set
                Me.reservationsField = value
                Me.RaisePropertyChanged("reservations")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dto.reservation")>  _
    Partial Public Class ClientDTO
        Inherits EntiteDTO
        
        Private clientField As Client
        
        Private idField As Integer
        
        Private nomField As String
        
        Private prenomField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property client() As Client
            Get
                Return Me.clientField
            End Get
            Set
                Me.clientField = value
                Me.RaisePropertyChanged("client")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property id() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property nom() As String
            Get
                Return Me.nomField
            End Get
            Set
                Me.nomField = value
                Me.RaisePropertyChanged("nom")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property prenom() As String
            Get
                Return Me.prenomField
            End Get
            Set
                Me.prenomField = value
                Me.RaisePropertyChanged("prenom")
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="obtenirListeClients", WrapperNamespace:="http://reservation", IsWrapped:=true)>  _
    Partial Public Class obtenirListeClientsRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="obtenirListeClientsResponse", WrapperNamespace:="http://reservation", IsWrapped:=true)>  _
    Partial Public Class obtenirListeClientsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://reservation", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("obtenirListeClientsReturn")>  _
        Public obtenirListeClientsReturn() As ServiceHotel.ClientDTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal obtenirListeClientsReturn() As ServiceHotel.ClientDTO)
            MyBase.New
            Me.obtenirListeClientsReturn = obtenirListeClientsReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="obtenirReservations", WrapperNamespace:="http://reservation", IsWrapped:=true)>  _
    Partial Public Class obtenirReservationsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://reservation", Order:=0)>  _
        Public idClient As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal idClient As Integer)
            MyBase.New
            Me.idClient = idClient
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="obtenirReservationsResponse", WrapperNamespace:="http://reservation", IsWrapped:=true)>  _
    Partial Public Class obtenirReservationsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://reservation", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("obtenirReservationsReturn")>  _
        Public obtenirReservationsReturn() As ServiceHotel.ReservationDTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal obtenirReservationsReturn() As ServiceHotel.ReservationDTO)
            MyBase.New
            Me.obtenirReservationsReturn = obtenirReservationsReturn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="obtenirListeChambre", WrapperNamespace:="http://reservation", IsWrapped:=true)>  _
    Partial Public Class obtenirListeChambreRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="obtenirListeChambreResponse", WrapperNamespace:="http://reservation", IsWrapped:=true)>  _
    Partial Public Class obtenirListeChambreResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://reservation", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("obtenirListeChambreReturn")>  _
        Public obtenirListeChambreReturn() As ServiceHotel.ChambreDTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal obtenirListeChambreReturn() As ServiceHotel.ChambreDTO)
            MyBase.New
            Me.obtenirListeChambreReturn = obtenirListeChambreReturn
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface FacadeServiceWebChannel
        Inherits ServiceHotel.FacadeServiceWeb, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FacadeServiceWebClient
        Inherits System.ServiceModel.ClientBase(Of ServiceHotel.FacadeServiceWeb)
        Implements ServiceHotel.FacadeServiceWeb
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function update(ByVal chambreDTO As ServiceHotel.Formulaire) As Boolean Implements ServiceHotel.FacadeServiceWeb.update
            Return MyBase.Channel.update(chambreDTO)
        End Function
        
        Public Function updateAsync(ByVal chambreDTO As ServiceHotel.Formulaire) As System.Threading.Tasks.Task(Of Boolean) Implements ServiceHotel.FacadeServiceWeb.updateAsync
            Return MyBase.Channel.updateAsync(chambreDTO)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceHotel_FacadeServiceWeb_obtenirListeClients(ByVal request As ServiceHotel.obtenirListeClientsRequest) As ServiceHotel.obtenirListeClientsResponse Implements ServiceHotel.FacadeServiceWeb.obtenirListeClients
            Return MyBase.Channel.obtenirListeClients(request)
        End Function
        
        Public Function obtenirListeClients() As ServiceHotel.ClientDTO()
            Dim inValue As ServiceHotel.obtenirListeClientsRequest = New ServiceHotel.obtenirListeClientsRequest()
            Dim retVal As ServiceHotel.obtenirListeClientsResponse = CType(Me,ServiceHotel.FacadeServiceWeb).obtenirListeClients(inValue)
            Return retVal.obtenirListeClientsReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceHotel_FacadeServiceWeb_obtenirListeClientsAsync(ByVal request As ServiceHotel.obtenirListeClientsRequest) As System.Threading.Tasks.Task(Of ServiceHotel.obtenirListeClientsResponse) Implements ServiceHotel.FacadeServiceWeb.obtenirListeClientsAsync
            Return MyBase.Channel.obtenirListeClientsAsync(request)
        End Function
        
        Public Function obtenirListeClientsAsync() As System.Threading.Tasks.Task(Of ServiceHotel.obtenirListeClientsResponse)
            Dim inValue As ServiceHotel.obtenirListeClientsRequest = New ServiceHotel.obtenirListeClientsRequest()
            Return CType(Me,ServiceHotel.FacadeServiceWeb).obtenirListeClientsAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceHotel_FacadeServiceWeb_obtenirReservations(ByVal request As ServiceHotel.obtenirReservationsRequest) As ServiceHotel.obtenirReservationsResponse Implements ServiceHotel.FacadeServiceWeb.obtenirReservations
            Return MyBase.Channel.obtenirReservations(request)
        End Function
        
        Public Function obtenirReservations(ByVal idClient As Integer) As ServiceHotel.ReservationDTO()
            Dim inValue As ServiceHotel.obtenirReservationsRequest = New ServiceHotel.obtenirReservationsRequest()
            inValue.idClient = idClient
            Dim retVal As ServiceHotel.obtenirReservationsResponse = CType(Me,ServiceHotel.FacadeServiceWeb).obtenirReservations(inValue)
            Return retVal.obtenirReservationsReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceHotel_FacadeServiceWeb_obtenirReservationsAsync(ByVal request As ServiceHotel.obtenirReservationsRequest) As System.Threading.Tasks.Task(Of ServiceHotel.obtenirReservationsResponse) Implements ServiceHotel.FacadeServiceWeb.obtenirReservationsAsync
            Return MyBase.Channel.obtenirReservationsAsync(request)
        End Function
        
        Public Function obtenirReservationsAsync(ByVal idClient As Integer) As System.Threading.Tasks.Task(Of ServiceHotel.obtenirReservationsResponse)
            Dim inValue As ServiceHotel.obtenirReservationsRequest = New ServiceHotel.obtenirReservationsRequest()
            inValue.idClient = idClient
            Return CType(Me,ServiceHotel.FacadeServiceWeb).obtenirReservationsAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceHotel_FacadeServiceWeb_obtenirListeChambre(ByVal request As ServiceHotel.obtenirListeChambreRequest) As ServiceHotel.obtenirListeChambreResponse Implements ServiceHotel.FacadeServiceWeb.obtenirListeChambre
            Return MyBase.Channel.obtenirListeChambre(request)
        End Function
        
        Public Function obtenirListeChambre() As ServiceHotel.ChambreDTO()
            Dim inValue As ServiceHotel.obtenirListeChambreRequest = New ServiceHotel.obtenirListeChambreRequest()
            Dim retVal As ServiceHotel.obtenirListeChambreResponse = CType(Me,ServiceHotel.FacadeServiceWeb).obtenirListeChambre(inValue)
            Return retVal.obtenirListeChambreReturn
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceHotel_FacadeServiceWeb_obtenirListeChambreAsync(ByVal request As ServiceHotel.obtenirListeChambreRequest) As System.Threading.Tasks.Task(Of ServiceHotel.obtenirListeChambreResponse) Implements ServiceHotel.FacadeServiceWeb.obtenirListeChambreAsync
            Return MyBase.Channel.obtenirListeChambreAsync(request)
        End Function
        
        Public Function obtenirListeChambreAsync() As System.Threading.Tasks.Task(Of ServiceHotel.obtenirListeChambreResponse)
            Dim inValue As ServiceHotel.obtenirListeChambreRequest = New ServiceHotel.obtenirListeChambreRequest()
            Return CType(Me,ServiceHotel.FacadeServiceWeb).obtenirListeChambreAsync(inValue)
        End Function
    End Class
End Namespace
